### ISSUE TITLE
Add section on configuration

### ISSUE THREAD

**Issue by ohsayan** [terrabasedb/docs#4]
Now that we're supporting configuration files, we need to document on how they should be used. 

For anyone who might be interested in solving this, a configuration file (for now) is a toml file with two required keys and one optional key:
```toml
[server]
host = "127.0.0.1" # Just an example, can be any valid IPv4 or IPv6 address
port = 2003 # Any valid port
# `noart` is an optional key that can be enabled in
# secure environments which do not permit
# terminal artwork
noart = false
```
Do note: if no configuration file is provided, the server would default to the above configuration.
Reference: terrabasedb/terrabase#19
